### ISSUE TITLE
Regularized evolution or reinforcement learning?

### ISSUE THREAD

**Issue by patrick-llgc** [cmu-enyac/LeGR#1]
In the paper the authors mentioned that the regularized evolution algorithm were used in Section 3.2, but in the code and also in Section 4.2, a deep reinforcement learning algorithm DDPG seems to be used. 

Did the authors try both algorithms? How do they compare with each other?

**Comment by RudyChin** [comment]
Hi Patrick,

Yes. I've tried both algorithms. Empirically, I found EA to be more robust than DDPG. That is, it has less variance in the accuracy of the pruned networks.
DDPG in the paper is mainly used to demonstrate the effectiveness of the proposed parameterization (learning affine transformations instead of learning sparsity).

Hope this helps!

Rudy

**Comment by patrick-llgc** [comment]
@RudyChin Thank you very much for the clarification, Rudy.

Btw, great work! Looking forward to it being published in a major conference. 

Patrick
