### ISSUE TITLE
code question

### ISSUE THREAD

**Issue by Slawlight** [cmu-enyac/LeGR#3]
In the function one_shot_lowest_ranking_filters(),  why use the dictionary self.chains()?  I didn't understand.

**Comment by RudyChin** [comment]
Hi,

Thank you for your interests, I could have written the comments more clearly.
`self.chains` is a dictionary that stores the dependency.
For example, if layer A is followed by a depth-wise convolution layer B, then layer A and layer B are chained together. Another example is the residual connection. The operand of the sum (two convolution layers) are chained together.

This chain is built for different networks (currently pseudo-hard-coded) in `fp_resnet.py` and `fp_mbnetb2.py`.

**Comment by Slawlight** [comment]
Thank you for your reply. 
For Resnet, the process of pruning is a little complicated. According to the paper, the importance of a filter is just a transformation of its l2 norm. But in the code these filters seem to be correlative because of the residual connection. Why do you calculate the importance like this?

**Comment by RudyChin** [comment]
Hi,

According to the explanation in above, when one prunes off a filter that is chained to some other filters, they all have to be pruned to ensure the resulting network still runs.
The idea behind the implementation is straightforward in the sense that we just add up the l2 of the filters that are chained together. It is because when one prunes away one of them, all of them has to be pruned.
Also, actually MobileNetV2 is more complicated since ResNet does not really need to tie the operands of the summation together, one can prune a filter and pad 0. However, this introduces a lot more implementation overhead and is obviously less attractive from a speed improvement perspective.

Hope this addresses your questions

**Comment by Slawlight** [comment]
I understand, thank you very much.
